### ISSUE TITLE
fab -f vocab/fabfile build_voca is not working in Python 3.6

### ISSUE THREAD

**Issue by kimfalk** [explosion/spacy-dev-resources#19]
running `fab -f vocab/fabfile build_vocab:da,/path/to/input_texts` will throw the following error when you run it in Python 3.6:

Traceback (most recent call last):
  File "training/plain_word_freqs.py", line 33, in <module>
    plac.call(main)
  File "/Users/u0157492/Karnov/git/data-science/venv/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/Users/u0157492/Karnov/git/data-science/venv/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "training/plain_word_freqs.py", line 28, in main
    for word, df in df_counts.iteritems():
AttributeError: 'Counter' object has no attribute 'iteritems'

To fix it change the line 28 in "training/plain_word_freqs.py", to 

`        for word, df in df_counts.items():`
